---
# tasks file for aws
- name: AWS - Configuration AWS_ACCESS_KEY_ID
  lineinfile:
    path: /home/retengr/.bashrc
    line: 'export AWS_ACCESS_KEY_ID={{ aws_access_key_id }}'

- name: AWS - Configuration AWS_SECRET_ACCESS_KEY
  lineinfile:
    path: /home/retengr/.bashrc
    line: 'export AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}'